### ISSUE TITLE
No points 

### ISSUE THREAD

**Issue by CC9310** [touristCheng/DepthFusion#1]
I modified the script "run.sh":
python fuse.py --root_path $root_path --save_path "./points" --dist_thresh 0.001 --prob_thresh 0.6 --num_consist 3 --device='cuda'

While I can't fuse all the depth into a point cloud.

(base) :~/UCSNet/DepthFusion$ bash ./run.sh
torch.Size([49, 1, 1184, 1600])
Scene: scan1 total: 49 frames
Processing scan1 1/49 ...
Processing scan1 2/49 ...
Processing scan1 3/49 ...
Processing scan1 4/49 ...
Processing scan1 5/49 ...
Processing scan1 6/49 ...
Processing scan1 7/49 ...
Processing scan1 8/49 ...
Processing scan1 9/49 ...
Processing scan1 10/49 ...
Processing scan1 11/49 ...
Processing scan1 12/49 ...
Processing scan1 13/49 ...
Processing scan1 14/49 ...
Processing scan1 15/49 ...
Processing scan1 16/49 ...
Processing scan1 17/49 ...
Processing scan1 18/49 ...
Processing scan1 19/49 ...
Processing scan1 20/49 ...
Processing scan1 21/49 ...
Processing scan1 22/49 ...
Processing scan1 23/49 ...
Processing scan1 24/49 ...
Processing scan1 25/49 ...
Processing scan1 26/49 ...
Processing scan1 27/49 ...
Processing scan1 28/49 ...
Processing scan1 29/49 ...
Processing scan1 30/49 ...
Processing scan1 31/49 ...
Processing scan1 32/49 ...
Processing scan1 33/49 ...
Processing scan1 34/49 ...
Processing scan1 35/49 ...
Processing scan1 36/49 ...
Processing scan1 37/49 ...
Processing scan1 38/49 ...
Processing scan1 39/49 ...
Processing scan1 40/49 ...
Processing scan1 41/49 ...
Processing scan1 42/49 ...
Processing scan1 43/49 ...
Processing scan1 44/49 ...
Processing scan1 45/49 ...
Processing scan1 46/49 ...
Processing scan1 47/49 ...
Processing scan1 48/49 ...
Processing scan1 49/49 ...
[Open3D WARNING] Write PLY failed: point cloud has 0 points.
Save ./points/scan1.ply successful.

Did I forget something?
Thanks.

**Comment by shreyaskamathkm** [comment]
Hi,

I am stuck with the same error. Were you able to fix this?

Thank you

**Comment by doubleZ0108** [comment]
Have you solve the problem?
Thanks

**Comment by doubleZ0108** [comment]
Change `num_consist` to some small number like 3, that is suitable for DTU dataset.
The origin `num_consist=10` was for TNT dataset.
Hope helpful.
